# Generated by Django 4.1.4 on 2023-05-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True)),
                ('author', models.CharField(db_index=True, max_length=128, unique=True)),
                ('pages_amount', models.PositiveIntegerField()),
            ],
        ),
    ]
